name: Generate Commits

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run loop for 105 commits
        run: |
          # CHANGE THIS to your actual GitHub email address:
          git config --local user.email "odionisaiahbright@gmail.com"
          git config --local user.name "1xtBe"
          
          for i in {1..105}
          do
            echo "User commit number $i" >> log.txt
            git add log.txt
            git commit -m "chore: verified public commit $i"
          done

      - name: Push changes
        run: |
          git push origin main

